---
loadbalancer:
  hosts:
    lb01:
      ansible_host: lb01
webserver:
  hosts:
    app01:
      ansible_host: app01
  vars:
    ansible_python_interpreter: /usr/bin/python3
database:
  hosts:
    db01:
      ansible_host: db01
      ansible_python_interpreter: /usr/bin/python3
deploymentservers:
  hosts:
    deploy1:
      ansible_host: 13.87.94.22
      ansible_port: 22
      ansible_ssh_user: azureuser
deploymentjenkins:
  hosts:
    deploy2:
      ansible_host: 
      ansible_port: 22
      ansible_ssh_user: jenkins      
control:
  hosts:
    local-control:
      ansible_connection: local
