---
- hosts: deploymentservers

  vars:
    app_dir: "{{user_dir}}/devopsSystem"
    
    git_repo_url: "https://github.com/it21998/devopsSystem.git"
    git_repo_branch: "main"

  tasks:

  - name: print user_dir
    debug:
      msg: "user dir is {{user_dir}}"

  - name: Run whoami without become.
    command: whoami
    changed_when: false
    become: false
    register: whoami

  - name: Set a fact with the user name.
    set_fact:
      login_user: "{{ whoami.stdout }}"

  - name: print user name
    debug:
      msg: "login user is {{login_user}}"

  - name: print user dir
    debug:
      msg: "login dir is {{user_dir}}"

  - name: ensure github.com is a known host
    lineinfile:
      dest: "{{user_dir}}/.ssh/known_hosts"
      create: yes
      state: present
      line: "{{lookup('pipe', 'ssh-keyscan -t rsa github.com')}}"
      regexp: "^github\\.com"

  - name: clone django project
    git:
      repo: "{{git_repo_url}}"
      version: "{{git_repo_branch}}"
      clone: yes
      force: yes
      dest: "{{app_dir}}"
    changed_when: true
  


  - name: copy env file
    shell : "cp {{app_dir}}/student_management/student_management/.env.example {{app_dir}}/student_management/student_management/.env"

  - name: populate  ~/.env
    lineinfile:
      dest: "{{app_dir}}/student_management/student_management/.env"
      state: present
      regexp: "^{{item.key}}="
      line: "{{item.key}}='{{item.value}}'"
    with_items:
      - "{{django.env | dict2items}}"

  - name: Get my public IP
    ipify_facts:

  - debug: var=ipify_public_ip

  # - name: print ip
  #   debug:
  #     msg: "ALLOWED_HOSTS={{ansible_all_ipv4_addresses}}"

  - name: add ip in django ALLOWED_HOSTS
    lineinfile:
      dest: "{{app_dir}}/student_management/student_management/settings.py"
      regexp: "^ALLOWED_HOSTS ="
      line: "ALLOWED_HOSTS = ['{{ipify_public_ip}}','127.0.1.1','localhost','10.3.0.4']"
      state: present

  - name: install and activate virtual environment
    block:
    - name: setup virtual environment
      pip:
        requirements: "{{app_dir}}/requirements.txt"
        virtualenv: "{{app_dir}}/myvenv"
        virtualenv_python: python3
    rescue:
    - name: "APT - install misc packages"
      apt:
        name: [python3, python3-pip, python3-virtualenv, virtualenv]
        update_cache: yes
      become: yes
      become_user: root
      when: hostvars[inventory_hostname].ansible_distribution == 'Ubuntu'
    always:

    - name: setup virtual environment
      pip:
        requirements: "{{app_dir}}/requirements.txt"
        virtualenv: "{{app_dir}}/myvenv"
        virtualenv_python: python3

    - name: make migrations
      django_manage:
        command: "{{ item }}"
        project_path: "{{app_dir}}/student_management"
        virtualenv: "{{app_dir}}/myvenv"
      with_items:
        - collectstatic
        - makemigrations
        - migrate
    
    - name: allow 9000
      shell : "ufw allow 9000"
      become: yes
      become_user: root

    - name: copy django service file
      template:
        src: ../files/django/guni.service.j2
        dest: "/etc/systemd/system/gunicorn2.service"
      become: yes
      become_user: root


    - name: ensure gunicorn service started
      service:
        name: gunicorn2
        state: started
        enabled: yes
      become: yes

  - name: install and configure nginx
    block:

    - name: "APT - install nginx"
      apt:
        name: nginx
        update_cache: yes

    - name: copy nginx conf file
      template:
        src: ../files/nginx/seconddemo.nginx.j2
        dest: "/etc/nginx/sites-available/djangosecond"

   

    - name: enable django site in nginx
      file:
        src: "/etc/nginx/sites-available/djangosecond"
        dest: "/etc/nginx/sites-enabled/djangosecond"
        state: link
      notify: restart nginx

   

    - name: de-activate default nginx site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify: restart nginx

    become: yes
    become_user: root



  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
      become: yes

    - name: restart gunicorn
      service:
        name: gunicorn
        state: restarted
      become: yes
