- hosts: all
  become: yes
  become_user: root
  vars:
    pip_executable: pip3
    pip_install_packages:
      - docker
      - docker-compose

  tasks:
  - name: Add universe repository for bionic
    apt_repository: 
      repo: deb http://archive.ubuntu.com/ubuntu bionic universe
      state: present
  - name: install gnupg2
    apt:
      name: gnupg2
      state: present
      update_cache: true
    when: ansible_distribution_release == 'bionic'
  
  - include_role:
      name: geerlingguy.docker
  - include_role:
      name: geerlingguy.pip
  - name: 'add users to docker group'
    user:
      name: 'vagrant'
      groups: 'docker'
      append: 'yes'