---
- hosts: webserver

  vars:
    user_dir: "/home/vagrant"
    app_dir: "{{user_dir}}/flask-project"
    git_repo_url: "https://github.com/tsadimas/flask-example-project.git"
    git_repo_branch: "main"
  
  tasks:

  - name: ensure github.com is a known host
    lineinfile:
      dest: "{{user_dir}}/.ssh/known_hosts"
      create: yes
      state: present
      line: "{{lookup('pipe', 'ssh-keyscan -t rsa github.com')}}"
      regexp: "^github\\.com"

  - name: clone flask project
    git:
      repo: "{{git_repo_url}}"
      version: "{{git_repo_branch}}"
      clone: yes
      #force: yes
      dest: "{{app_dir}}"
    changed_when: true

  - name: copy env file
    shell : "cp {{app_dir}}/.env.example {{app_dir}}/.env"

  - name: populate  ~/.env
    lineinfile:
      dest: "{{app_dir}}/.env"
      state: present
      regexp: "^{{item.key}}="
      line: "{{item.key}}='{{item.value}}'"
    with_items:
      - "{{app.env | dict2items}}"



  - name: install and activate virtual environment
    block:
    - name: setup virtual environment
      pip:
        requirements: "{{app_dir}}/requirements.txt"
        virtualenv: "{{app_dir}}/fvenv"
        virtualenv_python: python3
        state: forcereinstall
    rescue:
    - name: "APT - install misc packages"
      apt:
        name: [python3, python3-pip, python3-virtualenv, virtualenv, libmysqlclient-dev, mycli, pgcli, libpq-dev]
        update_cache: yes
      become: yes
      become_user: root
      when: hostvars[inventory_hostname].ansible_distribution == 'Ubuntu'
    always:

    - name: setup virtual environment
      pip:
        requirements: "{{app_dir}}/requirements.txt"
        virtualenv: "{{app_dir}}/fvenv"
        virtualenv_python: python3
        state: forcereinstall
    
    - name: copy flask service file
      template:
        src: ../files/flask/flaskgunicorn.service.j2
        dest: "/etc/systemd/system/flaskgunicorn.service"
      become: yes
      become_user: root
      notify: restart flaskgunicorn

    - name: ensure flaskgunicorn service started
      service: 
        name: flaskgunicorn
        state: started
        enabled: yes
      become: yes

  - name: install and configure nginx
    block:

    - name: "APT - install nginx"
      apt:
        name: nginx
        update_cache: yes

    - name: copy nginx conf file
      template:
        src: ../files/nginx/demo.nginx.j2
        dest: "/etc/nginx/sites-available/flask"

    - name: copy nginx https conf file
      template:
        src: ../files/nginx/demo.https.nginx.j2
        dest: "/etc/nginx/sites-available/flaskssl"


    - name: copy certificates
      copy:
        src: "{{item}}"
        dest: /etc/ssl/private/
      with_items:
        - ../files/certs/server.crt
        - ../files/certs/server.key
      
  
    - name: enable flask site in nginx
      file:
        src: "/etc/nginx/sites-available/flask"
        dest: "/etc/nginx/sites-enabled/flask"
        state: link
      notify: restart nginx

    - name: enable flaskssl site in nginx
      file:
        src: "/etc/nginx/sites-available/flaskssl"
        dest: "/etc/nginx/sites-enabled/flaskssl"
        state: link
      notify: restart nginx

    - name: de-activate default nginx site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify: restart nginx
    
    become: yes
    become_user: root


  handlers:

  - name: restart nginx
    service:
      name: nginx
      state: restarted
    become: yes
  
  - name: restart flaskgunicorn
    service:
      name: flaskgunicorn
      state: restarted
    become: yes



