---
- hosts: app01
  become: true
  
  
  tasks:

  - name: print mysql password
    debug:
      msg: mysql root pass is {{mysql_root_password}}

  - name: Specify MySQL root password before installing
    debconf: 
      name: 'mysql-server'
      question: 'mysql-server/root_password' 
      value: '{{mysql_root_password | quote}}' 
      vtype: 'password'
    

  - name: Confirm MySQL root password before installing
    debconf: 
      name: 'mysql-server' 
      question: 'mysql-server/root_password_again'
      value: '{{mysql_root_password | quote}}'
      vtype: 'password'
    
    
  - name: install mysql-server
    apt: 
      name: ['mysql-server', 'mysql-client'] 
      state: present 
      update_cache: yes

  - name: ensure mysql started
    service:
      name: mysql
      state: started
      enabled: yes

  - name: ensure mysql listening on all ports
    lineinfile: dest=/etc/mysql/mysql.conf.d/mysqld.cnf regexp=^bind-address line="bind-address = 0.0.0.0"
    notify: restart mysql

  - name: Determine required MySQL Python libraries.
    set_fact:
      deb_mysql_python_package: "{% if 'python3' in ansible_python_interpreter|default('') %}python3-mysqldb{% else %}python-mysqldb{% endif %}"

  - name: Ensure MySQL Python libraries are installed.
    apt: 
      name: "{{ deb_mysql_python_package }}"
      state: present
      update_cache: yes 

  - name: create demo database
    mysql_db: 
      login_host: 'localhost'
      login_user: 'root'
      login_password: "{{mysql_root_password}}"
      name: demo 
      state: present
      

  - name: create demo user
    mysql_user:
      login_host: 'localhost'
      login_user: 'root'
      login_password: "{{mysql_root_password}}" 
      name: demo 
      password: demo 
      priv: demo.*:ALL 
      host: '%' 
      state: present

  handlers:
    - name: restart mysql
      service: 
        name: mysql 
        state: restarted
